### create a workoutExercise
POST http://localhost:3000/workoutExercises
Content-Type: application/json

{
  "workoutId": 7,
  "exerciseId": 7
}

### get all workoutExercises
GET http://localhost:3000/workoutExercises

### get workoutExercise by id
GET http://localhost:3000/workoutExercises/remplace_par_workoutExercise_id

### update workoutExercise by id
PUT http://localhost:3000/workoutExercises/remplace_par_workoutExercise_id
Content-Type: application/json

{
  "exerciseId": "remplace_par_nouvel_exercise_id"
}

### delete workoutExercise by id
DELETE http://localhost:3000/workoutExercises/eb5e1962-3b19-49b6-bd1e-bfdb7335924b